version: 2
jobs:
  build_and_test:
    docker:
      - image: wunderio/silta-circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-composer-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - run: composer install --ignore-platform-reqs
      - run: ./vendor/bin/grumphp run
      - save_cache:
          paths:
            - ~/project/drupal/vendor
            - ~/project/drupal/web/core
            - ~/project/drupal/web/modules/contrib
            - ~/project/drupal/web/themes/contrib
            - ~/project/drupal/web/profiles/contrib
            - ~/project/drupal/web/libraries
          key: v2-composer-dependencies-{{ .Environment.CIRCLE_SHA1 }}
  analyze:
    docker:
      - image: dmoscrop/circleci-sonar-scanner-docker
        environment:
          SONAR_ANALYSIS_MODE: publish
      - image: wunderio/silta-circleci

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-composer-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - run: composer install --ignore-platform-reqs
      - run: ./vendor/bin/phpunit --coverage-clover /tmp/coverage.xml
      - save_cache:
          paths:
            - ~/project/drupal/vendor
            - ~/project/drupal/web/core
            - ~/project/drupal/web/modules/contrib
            - ~/project/drupal/web/themes/contrib
            - ~/project/drupal/web/profiles/contrib
            - ~/project/drupal/web/libraries
          key: v2-composer-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - run: run-sonar-scanner -Dsonar.projectKey=code-quality -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.php.coverage.reportPaths=/tmp/coverage.xml

# Workflow
workflows:
  version: 2
  test_and_analyze:
    jobs:
      - build_and_test
      - analyze:
          requires:
            - build_and_test
#          filters:
#            branches:
#              only: master
