version: 2
jobs:
  build_and_test:
    docker:
      - image: wunderio/silta-circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-composer-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - run: composer install --ignore-platform-reqs
      - run: ./vendor/bin/grumphp run
      - save_cache:
          paths:
            - ~/project/vendor
          key: v2-composer-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - save_cache:
          paths:
            - ~/project
          key: v2-coverage--{{ .Environment.CIRCLE_SHA1 }}
  analyze:
    docker:
      - image: dmoscrop/circleci-sonar-scanner-docker
        environment:
          SONAR_ANALYSIS_MODE: publish
          SONAR_SCANNER_VERSION: 4.0.0.1744

    steps:
      - checkout
      - restore_cache:
          key: v2-coverage--{{ .Environment.CIRCLE_SHA1 }}
      - run: cd /home/circleci/project/ && sonar-scanner -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.php.coverage.reportPaths=/home/circleci/project/coverage.xml -Dsonar.projectKey=code-quality

# Workflow
workflows:
  version: 2
  test_and_analyze:
    jobs:
      - build_and_test
      - analyze:
          requires:
            - build_and_test
#          filters:
#            branches:
#              only: master
